[package]
name = "stackctl"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stackable-cli = { git = "https://github.com/futursolo/stackable" }
tokio = "1"
anyhow = "1"
